### ISSUE TITLE
pod升级到1.7.2之后，项目运行不起来

### ISSUE THREAD

**Issue by OPY-bbt** [v7lin/fake_wechat#16]
pod 1.7.2

[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.6 18G95, locale en-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.38.1)
[✓] Connected device (1 available)

![image](https://user-images.githubusercontent.com/16717283/65409852-64e93880-de1b-11e9-92cb-a8f80642e51b.png)

**Comment by v7lin** [comment]
pod install / pod repo update

**Comment by OPY-bbt** [comment]
还是不行
```
Launching lib/main.dart on iPhone 11 in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                            5.8s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    === BUILD TARGET flutter_webview_plugin OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Adjust/Adjust/ADJDeviceInfo.m:71:50: warning: 'appStoreReceiptURL' is only available on iOS 7.0 or newer [-Wunguarded-availability]
            NSURL * installReceiptLocation = [bundle appStoreReceiptURL];
                                                     ^~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Adjust/Adjust/ADJDeviceInfo.h:9:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.0.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:64:45: note: 'appStoreReceiptURL' has been marked as being introduced in iOS 7.0 here, but the deployment target is iOS 6.0.0
    @property (nullable, readonly, copy) NSURL *appStoreReceiptURL API_AVAILABLE(macos(10.7), ios(7.0), watchos(2.0), tvos(9.0));
                                                ^
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Adjust/Adjust/ADJDeviceInfo.m:71:50: note: enclose 'appStoreReceiptURL' in an @available check to silence this warning
            NSURL * installReceiptLocation = [bundle appStoreReceiptURL];
                                                     ^~~~~~~~~~~~~~~~~~~
    1 warning generated.
    In file included from /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:2:
    In file included from /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApi.h:10:
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApiObject.h:385:14: warning: empty paragraph passed to '@attention' command [-Wdocumentation]
     * @attention
       ~~~~~~~~~~^
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApiObject.h:390:14: warning: empty paragraph passed to '@attention' command [-Wdocumentation]
     * @attention
       ~~~~~~~~~~^
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApiObject.h:408:14: warning: empty paragraph passed to '@attention' command [-Wdocumentation]
     * @attention
       ~~~~~~~~~~^
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApiObject.h:1009:9: warning: empty paragraph passed to '@note' command [-Wdocumentation]
     * @note
       ~~~~~^
    In file included from /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:2:
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApi.h:37:56: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     * @param resp具体的回应内容，是自动释放的
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApi.h:37:11: warning: parameter 'resp具体的回应内容，是自动释放的' not found in the function declaration [-Wdocumentation]
     * @param resp具体的回应内容，是自动释放的
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApi.h:37:11: note: did you mean 'resp'?
     * @param resp具体的回应内容，是自动释放的
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              resp
    /Users/zhangyan/Desktop/projects/ips_app/ios/Pods/Headers/Private/WechatOpenSDK/WXApi.h:178:11: warning: empty paragraph passed to '@param' command [-Wdocumentation]
     *  @param 
        ~~~~~~^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:123:16: error: no known class method for selector 'registerApp:enableMTA:'
            [WXApi registerApp:appId enableMTA:NO];
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:168:12: error: no known class method for selector 'sendReq:'
        [WXApi sendReq:req];
               ^~~~~~~
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:189:12: error: no known class method for selector 'sendReq:'
        [WXApi sendReq:req];
               ^~~~~~~
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:195:12: error: no known class method for selector 'sendReq:'
        [WXApi sendReq:req];
               ^~~~~~~
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:200:5: error: use of undeclared identifier 'JumpToBizProfileReq'
        JumpToBizProfileReq * req = [[JumpToBizProfileReq alloc] init];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:200:27: error: use of undeclared identifier 'req'
        JumpToBizProfileReq * req = [[JumpToBizProfileReq alloc] init];
                              ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:200:35: error: use of undeclared identifier 'JumpToBizProfileReq'
        JumpToBizProfileReq * req = [[JumpToBizProfileReq alloc] init];
                                      ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:202:5: error: use of undeclared identifier 'req'
        req.profileType = [profileType intValue];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:203:5: error: use of undeclared identifier 'req'
        req.username = call.arguments[ARGUMENT_KEY_USERNAME];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:204:5: error: use of undeclared identifier 'req'
        req.extMsg = call.arguments[ARGUMENT_KEY_EXTMSG];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:205:12: error: no known class method for selector 'sendReq:'
        [WXApi sendReq:req];
               ^~~~~~~
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:205:20: error: use of undeclared identifier 'req'
        [WXApi sendReq:req];
                       ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:210:5: error: use of undeclared identifier 'JumpToBizWebviewReq'
        JumpToBizWebviewReq * req = [[JumpToBizWebviewReq alloc] init];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:210:27: error: use of undeclared identifier 'req'
        JumpToBizWebviewReq * req = [[JumpToBizWebviewReq alloc] init];
                              ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:210:35: error: use of undeclared identifier 'JumpToBizWebviewReq'
        JumpToBizWebviewReq * req = [[JumpToBizWebviewReq alloc] init];
                                      ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:212:5: error: use of undeclared identifier 'req'
        req.webType = [webType intValue];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:213:5: error: use of undeclared identifier 'req'
        req.tousrname = call.arguments[ARGUMENT_KEY_USERNAME];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:214:5: error: use of undeclared identifier 'req'
        req.extMsg = call.arguments[ARGUMENT_KEY_EXTMSG];
        ^
    /Users/zhangyan/Documents/flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_wechat-0.3.3/ios/Classes/FakeWechatPlugin.m:215:12: error: no known class method for selector 'sendReq:'
        [WXApi sendReq:req];
               ^~~~~~~
    fatal error: too many errors emitted, stopping now [-ferror-limit=]
    7 warnings and 20 errors generated.

Could not build the application for the simulator.
Error launching application on iPhone 11.
```

**Comment by v7lin** [comment]
应该是你的环境有问题，我升级到1.8.0，没有报错

**Comment by OPY-bbt** [comment]
嗯 我觉得也是。我再找找原因。

**Comment by OPY-bbt** [comment]
@v7lin 想问一下点击registerApp 方法 的Jump to Definition ，会提示没找到。但是WXApi却可以找到。。。你知道这是什么原因吗
![DCAF122E-EE5A-4094-B1BE-EA8F7F67231A](https://user-images.githubusercontent.com/16717283/65566418-57e85880-df85-11e9-936f-d6e8cc361d4c.png)

**Comment by OPY-bbt** [comment]
@v7lin  找到原因了，库与WechatOpenSDK (1.8.6)不兼容，退回到 1.8.4版本就好了，建议指定依赖的WechatOpenSDK版本。

**Comment by v7lin** [comment]
😳 微信这么坑

**Comment by OPY-bbt** [comment]
没办法，总归是要升级的。。。你先写死1.8.4版本吧，要不然后面来的同学都不能用～

**Comment by v7lin** [comment]
嗯，有道理，晚上我回去看看，有时间就升级，没时间就固定版本

**Comment by ismanong** [comment]
@OPY-bbt  这个怎么降级呢 请问一下  我直接在fake_wechat.podspec 里降级  老提示我依赖版本不足  只能装1.8.6才能报你那个错误

**Comment by v7lin** [comment]
用 git 方式引入 github 项目吧，最新版 fake_wechat 差文档还没写完，所以还没 release

**Comment by ismanong** [comment]
谢谢这么晚回复。 我明天试一试，就链接这个项目的git链接对吧。你也早点休息噢，我研究了好几个小时，新的ul的方式，对我而言，用着有点勉强。谢谢

**Comment by CodeGather** [comment]
这个问题解决了吗？为什么我的还是提示这样的错误

**Comment by v7lin** [comment]
最新的插件还没正式 release，先用 git 方式应用 master 最新代码 。。。

**Comment by CodeGather** [comment]
好的，还有这个是不是不支持在模拟器上运行呢

**Comment by v7lin** [comment]
没试过，应该是支持的，这个取决于微信SDK的支持与否

**Comment by ismanong** [comment]
解决是解决了 不会报错，用这个
#  fake_wechat:
#    git: git://github.com/v7lin/fake_wechat.git
但但但是  如果开启了swift  可以编译成功，但会启动闪退，建议不要开启swift

**Comment by v7lin** [comment]
@ismanong 有没有日志信息？我查查原因

**Comment by CodeGather** [comment]
这是我用模拟器跑的，能跑起来但是使用功能的时候出问题，也不知道什么原因
2019-10-29 10:16:17.457830+0800 dali[71902:1210589] flutter: Observatory listening on http://127.0.0.1:59598/QY8ME4MRdgs=/
2019-10-29 10:16:18.265414+0800 dali[71902:1210561] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-29 10:16:18.265447+0800 dali[71902:1210558] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-29 10:16:18.265563+0800 dali[71902:1210558] [Client] Updating selectors after delegate addition failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-29 10:16:18.265998+0800 dali[71902:1210561] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-29 10:16:18.266041+0800 dali[71902:1210558] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-29 10:16:18.266414+0800 dali[71902:1210561] [Client] Synchronous remote object proxy returned error: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-29 10:16:18.266523+0800 dali[71902:1210558] [Client] Updating selectors failed with: Error Domain=NSCocoaErrorDomain Code=4099 "The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated." UserInfo={NSDebugDescription=The connection to service on pid 0 named com.apple.commcenter.coretelephony.xpc was invalidated.}
2019-10-29 10:16:18.581249+0800 dali[71902:1210561] [] nw_proxy_resolver_create_parsed_array [C1 proxy pac] Evaluation error: NSURLErrorDomain: -1003
2019-10-29 10:16:24.048365+0800 dali[71902:1210369] -[NSNull length]: unrecognized selector sent to instance 0x7fff805ed8a0
2019-10-29 10:16:24.089238+0800 dali[71902:1210369] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x7fff805ed8a0'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23b98bde __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff503b5b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23bb9704 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x00007fff23b9d7bc ___forwarding___ + 1436
	4   CoreFoundation                      0x00007fff23b9f6c8 _CF_forwarding_prep_0 + 120
	5   dali                                0x0000000102277376 +[WXApi registerApp:universalLink:] + 94
	6   dali                                0x00000001022a4f6c -[FakeWechatPlugin handleMethodCall:result:] + 412
	7   Flutter                             0x0000000103b524fd __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	8   Flutter                             0x0000000103aebec0 _ZNK7flutter21PlatformMessageRouter21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 166
	9   Flutter                             0x0000000103aef780 _ZN7flutter15PlatformViewIOS21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 38
	10  Flutter                             0x0000000103b4cdb3 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_31NS_9allocatorIS8_EEFvvEEclEv + 57
	11  Flutter                             0x0000000103afe3f1 _ZN3fml15MessageLoopImpl10FlushTasksENS_9FlushTypeE + 123
	12  Flutter                             0x0000000103b03742 _ZN3fml17MessageLoopDarwin11OnTimerFireEP16__CFRunLoopTimerPS0_ + 26
	13  CoreFoundation                      0x00007fff23afc1e4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 20
	14  CoreFoundation                      0x00007fff23afbed2 __CFRunLoopDoTimer + 1026
	15  CoreFoundation                      0x00007fff23afb52a __CFRunLoopDoTimers + 266
	16  CoreFoundation                      0x00007fff23af629e __CFRunLoopRun + 2238
	17  CoreFoundation                      0x00007fff23af56b6 CFRunLoopRunSpecific + 438
	18  GraphicsServices                    0x00007fff3815cbb0 GSEventRunModal + 65
	19  UIKitCore                           0x00007fff47162a67 UIApplicationMain + 1621
	20  dali                                0x000000010222b548 main + 72
	21  libdyld.dylib                       0x00007fff5123bcf5 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by v7lin** [comment]
@CodeGather 你没设置 universalLink 吧？

**Comment by CodeGather** [comment]
@v7lin 果然就是这个问题，设置完后在模拟器上测试正常，谢谢

**Comment by ismanong** [comment]
@v7lin  会不会跟ul相关？
2019-10-29 10:24:33.391976+0800 Runner[334:11914] Metal API Validation Enabled
2019-10-29 10:24:33.563085+0800 Runner[334:12150] flutter: Observatory listening on http://127.0.0.1:50666/RjZlGAq8I-M=/
2019-10-29 10:24:34.879914+0800 Runner[334:12142] flutter: null / com.liil.shop.app / 1.9.0 / 7
2019-10-29 10:24:34.904329+0800 Runner[334:12142] flutter: ========================初始化 第三方SDK=============================
2019-10-29 10:24:34.908975+0800 Runner[334:11914] -[NSNull length]: unrecognized selector sent to instance 0x1e37fb9a0
2019-10-29 10:24:34.910484+0800 Runner[334:11914] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull length]: unrecognized selector sent to instance 0x1e37fb9a0'
*** First throw call stack:
(0x1a76a898c 0x1a73d10a4 0x1a75ac43c 0x1a76ace08 0x1a76aebec 0x102ca3bdc 0x102cf55b0 0x1032bae94 0x103256e74 0x1032ac25c 0x1032656a8 0x103268088 0x1a7626e1c 0x1a7626b58 0x1a7626228 0x1a7621364 0x1a76208bc 0x1b148c328 0x1ab6b66d4 0x102c8ce3c 0x1a74ab460)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by v7lin** [comment]
@ismanong 你的问题同 @CodeGather 一样，我后续会在 flutter 代码里面添加 assert 判断 universalLink

**Comment by ismanong** [comment]
嗯 但是oc的版本 我用0.33  毫无问题

**Comment by v7lin** [comment]
那是你没升级 cocopods 仓库，升级后就得升级插件了

**Comment by CodeGather** [comment]
这个错误完全看不懂，丝毫没有提到关于universalLink的信息

**Comment by ismanong** [comment]
我还是用oc的，因为还有一个淘宝包，在支持swift的flutter项目上调用闪退。这个可跟ul没关系，升级的心态都炸了，有问题的都归类了，太难了。
